import { ProtectedRoute } from "@/components/guards/ProtectedRoute";
import { SuperAdminLayout } from "@/components/layout/superadmin/SuperAdminLayout";

export const metadata = {
  title: "Nepdine Admin",
  description: "Generated by Next.js",
};

export default function SuperAdminRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute requireSuperAdmin>
      <SuperAdminLayout>{children}</SuperAdminLayout>
    </ProtectedRoute>
  );
}
