import { ProtectedRoute } from "@/components/guards/ProtectedRoute";

export const metadata = {
  title: "Nepdine Admin",
  description: "Generated by Next.js",
};

export default function SuperAdminRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute requireAuth requireRole="admin">
      {children}
    </ProtectedRoute>
  );
}
