import "@/app/globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ReactQueryClientProvider from "../../providers/ReactQueryClientProvider";
import { UserProvider } from "@/components/guards/UserContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
// Load Poppins with desired weights
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Nepdine",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={` ${poppins.className} antialiased bg-[#f9fafb] text-zinc-900 `}
      >
        <GoogleOAuthProvider clientId="451157442441-lt5f96l9oevidllc9d8ulofgf47ltk4m.apps.googleusercontent.com">
          <ReactQueryClientProvider>
            <UserProvider>
              <Toaster />
              {children}
            </UserProvider>
          </ReactQueryClientProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
